version: '3.8'
services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    restart: always
    environment:
      LDAP_ORGANISATION: "Example Inc."
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "admin123"
    ports:
      - "389:389"


volumes:
  ldap_data:
  ldap_config:
